1: log_date
2: pid
3: pno
4: list_price
5: c_platform_price
6: discount
7: is_sale
8: create_date
9: sku_num
10: catid1
11: catid2
12: catid3
13: cat1_price
14: cat2_price
15: cat3_price
16: imp_uv_1d
17: click_uv_1d
18: ctr_uv_1d
19: acr_uv_1d
20: wr_uv_1d
21: imp_uv_7d
22: click_uv_7d
23: ctr_uv_7d
24: acr_uv_7d
25: wr_uv_7d
26: imp_uv_15d
27: click_uv_15d
28: ctr_uv_15d
29: acr_uv_15d
30: wr_uv_15d
31: imp_uv_30d
32: click_uv_30d
33: ctr_uv_30d
34: acr_uv_30d
35: wr_uv_30d
36: imp_uv_60d
37: click_uv_60d
38: ctr_uv_60d
39: acr_uv_60d
40: wr_uv_60d
41: imp_uv_90d
42: click_uv_90d
43: ctr_uv_90d
44: acr_uv_90d
45: wr_uv_90d
46: comment_cnt_1d
47: score_description_1d
48: score_quality_1d
49: score_size_1d
50: score_1d
51: good_score_rate_1d
52: imp_1d
53: click_1d
54: add_1d
55: add_uv_1d
56: wishlist_1d
57: wishlist_uv_1d
58: ctr_1d
59: acr_1d
60: wr_1d
61: sales_1d
62: in_sales_1d
63: orders_1d
64: price_1d
65: gmv_1d
66: buyers_1d
67: in_buyers_1d
68: buyer_male_1d
69: buyer_female_1d
70: buyer_neutral_1d
71: male_rate_1d
72: female_rate_1d
73: neutral_rate_1d
74: confirm_sales_1d
75: in_confirm_sales_1d
76: confirm_orders_1d
77: confirm_price_1d
78: confirm_gmv_1d
79: confirm_buyers_1d
80: in_confirm_buyers_1d
81: confirm_buyer_male_1d
82: confirm_buyer_female_1d
83: confirm_buyer_neutral_1d
84: confirm_male_rate_1d
85: confirm_female_rate_1d
86: confirm_neutral_rate_1d
87: refund_1d
88: refund_rate_1d
89: repurchase_rate_1d
90: comment_cnt_7d
91: score_description_7d
92: score_quality_7d
93: score_size_7d
94: score_7d
95: good_score_rate_7d
96: imp_7d
97: click_7d
98: add_7d
99: add_uv_7d
100: wishlist_7d
101: wishlist_uv_7d
102: ctr_7d
103: acr_7d
104: wr_7d
105: sales_7d
106: in_sales_7d
107: orders_7d
108: price_7d
109: gmv_7d
110: buyers_7d
111: in_buyers_7d
112: buyer_male_7d
113: buyer_female_7d
114: buyer_neutral_7d
115: male_rate_7d
116: female_rate_7d
117: neutral_rate_7d
118: confirm_sales_7d
119: in_confirm_sales_7d
120: confirm_orders_7d
121: confirm_price_7d
122: confirm_gmv_7d
123: confirm_buyers_7d
124: in_confirm_buyers_7d
125: confirm_buyer_male_7d
126: confirm_buyer_female_7d
127: confirm_buyer_neutral_7d
128: confirm_male_rate_7d
129: confirm_female_rate_7d
130: confirm_neutral_rate_7d
131: refund_7d
132: refund_rate_7d
133: repurchase_rate_7d
134: comment_cnt_15d
135: score_description_15d
136: score_quality_15d
137: score_size_15d
138: score_15d
139: good_score_rate_15d
140: imp_15d
141: click_15d
142: add_15d
143: add_uv_15d
144: wishlist_15d
145: wishlist_uv_15d
146: ctr_15d
147: acr_15d
148: wr_15d
149: sales_15d
150: in_sales_15d
151: orders_15d
152: price_15d
153: gmv_15d
154: buyers_15d
155: in_buyers_15d
156: buyer_male_15d
157: buyer_female_15d
158: buyer_neutral_15d
159: male_rate_15d
160: female_rate_15d
161: neutral_rate_15d
162: confirm_sales_15d
163: in_confirm_sales_15d
164: confirm_orders_15d
165: confirm_price_15d
166: confirm_gmv_15d
167: confirm_buyers_15d
168: in_confirm_buyers_15d
169: confirm_buyer_male_15d
170: confirm_buyer_female_15d
171: confirm_buyer_neutral_15d
172: confirm_male_rate_15d
173: confirm_female_rate_15d
174: confirm_neutral_rate_15d
175: refund_15d
176: refund_rate_15d
177: repurchase_rate_15d
178: comment_cnt_30d
179: score_description_30d
180: score_quality_30d
181: score_size_30d
182: score_30d
183: good_score_rate_30d
184: imp_30d
185: click_30d
186: add_30d
187: add_uv_30d
188: wishlist_30d
189: wishlist_uv_30d
190: ctr_30d
191: acr_30d
192: wr_30d
193: sales_30d
194: in_sales_30d
195: orders_30d
196: price_30d
197: gmv_30d
198: buyers_30d
199: in_buyers_30d
200: buyer_male_30d
201: buyer_female_30d
202: buyer_neutral_30d
203: male_rate_30d
204: female_rate_30d
205: neutral_rate_30d
206: confirm_sales_30d
207: in_confirm_sales_30d
208: confirm_orders_30d
209: confirm_price_30d
210: confirm_gmv_30d
211: confirm_buyers_30d
212: in_confirm_buyers_30d
213: confirm_buyer_male_30d
214: confirm_buyer_female_30d
215: confirm_buyer_neutral_30d
216: confirm_male_rate_30d
217: confirm_female_rate_30d
218: confirm_neutral_rate_30d
219: refund_30d
220: refund_rate_30d
221: repurchase_rate_30d
222: comment_cnt_60d
223: score_description_60d
224: score_quality_60d
225: score_size_60d
226: score_60d
227: good_score_rate_60d
228: imp_60d
229: click_60d
230: add_60d
231: add_uv_60d
232: wishlist_60d
233: wishlist_uv_60d
234: ctr_60d
235: acr_60d
236: wr_60d
237: sales_60d
238: in_sales_60d
239: orders_60d
240: price_60d
241: gmv_60d
242: buyers_60d
243: in_buyers_60d
244: buyer_male_60d
245: buyer_female_60d
246: buyer_neutral_60d
247: male_rate_60d
248: female_rate_60d
249: neutral_rate_60d
250: confirm_sales_60d
251: in_confirm_sales_60d
252: confirm_orders_60d
253: confirm_price_60d
254: confirm_gmv_60d
255: confirm_buyers_60d
256: in_confirm_buyers_60d
257: confirm_buyer_male_60d
258: confirm_buyer_female_60d
259: confirm_buyer_neutral_60d
260: confirm_male_rate_60d
261: confirm_female_rate_60d
262: confirm_neutral_rate_60d
263: refund_60d
264: refund_rate_60d
265: repurchase_rate_60d
266: comment_cnt_90d
267: score_description_90d
268: score_quality_90d
269: score_size_90d
270: score_90d
271: good_score_rate_90d
272: imp_90d
273: click_90d
274: add_90d
275: add_uv_90d
276: wishlist_90d
277: wishlist_uv_90d
278: ctr_90d
279: acr_90d
280: wr_90d
281: sales_90d
282: in_sales_90d
283: orders_90d
284: price_90d
285: gmv_90d
286: buyers_90d
287: in_buyers_90d
288: buyer_male_90d
289: buyer_female_90d
290: buyer_neutral_90d
291: male_rate_90d
292: female_rate_90d
293: neutral_rate_90d
294: confirm_sales_90d
295: in_confirm_sales_90d
296: confirm_orders_90d
297: confirm_price_90d
298: confirm_gmv_90d
299: confirm_buyers_90d
300: in_confirm_buyers_90d
301: confirm_buyer_male_90d
302: confirm_buyer_female_90d
303: confirm_buyer_neutral_90d
304: confirm_male_rate_90d
305: confirm_female_rate_90d
306: confirm_neutral_rate_90d
307: refund_90d
308: refund_rate_90d
309: repurchase_rate_90d
310: comment_cnt
311: score_description
312: score_quality
313: score_size
314: score
315: good_score_rate
316: imp
317: click
318: add
319: add_uv
320: wishlist
321: wishlist_uv
322: ctr
323: acr
324: wr
325: sales
326: in_sales
327: orders
328: price
329: gmv
330: buyers
331: in_buyers
332: buyer_male
333: buyer_female
334: buyer_neutral
335: male_rate
336: female_rate
337: neutral_rate
338: confirm_sales
339: in_confirm_sales
340: confirm_orders
341: confirm_price
342: confirm_gmv
343: confirm_buyers
344: in_confirm_buyers
345: confirm_buyer_male
346: confirm_buyer_female
347: confirm_buyer_neutral
348: confirm_male_rate
349: confirm_female_rate
350: confirm_neutral_rate
351: refund
352: refund_rate
353: repurchase_rate
354: page_imp_1d
355: page_imp_uv_1d
356: page_imp_7d
357: page_imp_uv_7d
358: page_imp_15d
359: page_imp_uv_15d
360: page_imp_30d
361: page_imp_uv_30d
362: page_imp_60d
363: page_imp_uv_60d
364: page_imp_90d
365: page_imp_uv_90d
366: page_imp
367: page_imp_uv
368: season
369: gender
370: illegal_tags
371: shipping_sales_1d
372: shipping_orders_1d
373: shipping_sales_7d
374: shipping_orders_7d
375: shipping_sales_15d
376: shipping_orders_15d
377: shipping_sales_30d
378: shipping_orders_30d
379: shipping_sales_60d
380: shipping_orders_60d
381: shipping_sales_90d
382: shipping_orders_90d
383: shipping_sales
384: shipping_orders
385: confirm_price_unit_india_var_1d
386: confirm_price_unit_india_var_7d
387: confirm_price_unit_india_var_15d
388: confirm_price_unit_india_var_30d
389: confirm_price_unit_india_var_60d
390: confirm_price_unit_india_var_90d
391: confirm_price_unit_india_var
392: confirm_price_unit_india_avg_1d
393: confirm_price_unit_india_avg_7d
394: confirm_price_unit_india_avg_15d
395: confirm_price_unit_india_avg_30d
396: confirm_price_unit_india_avg_60d
397: confirm_price_unit_india_avg_90d
398: confirm_price_unit_india_avg
